### ISSUE TITLE
No ACL lists sent

### ISSUE THREAD

**Issue by rlambrechts** [googlegsa/library#1]
I am sending ACL rules from within the getDocContent() function. However these aren't enforced by the GSA.

The code I am using is:

```
@Override
public void getDocContent(Request req, Response resp) throws IOException {
    //do stuff here...

    String content = ContentBuilder.buildContent(vo);
    resp.setAcl(vo.getAcl());
    resp.getOutputStream().write(content.getBytes());
}
```

```
    public static Acl build(UserCache cache, List<String> users) {
        Acl.Builder list = new Acl.Builder();
        String userdomain = cache.getAccountsDomain();

        List<UserPrincipal> userPermits = new ArrayList<UserPrincipal>();
        List<GroupPrincipal> groupPermits = new ArrayList<GroupPrincipal>();

        for (String permission : rules) {
            GroupPrincipal principal = new GroupPrincipal(userdomain + "\\" + permission);
            groupPermits.add(principal);
        }

        userPermits.add(new UserPrincipal(cache.getMasterAccount()));

        list.setPermitUsers(userPermits);
        list.setPermitGroups(groupPermits);

        return list.setEverythingCaseInsensitive().setInheritanceType(Acl.InheritanceType.PARENT_OVERRIDES).build();
    }
```

When I debug; the ACL list is sent, So I am sure it is sending and the list isn't zero.

In the GSA front-end I can search the content and the ACL rules aren't enforced.

**Comment by TanmayVartak** [comment]
Hi,

I tried your code and I do see ACLs on GSA. To analyze this further can you please provide additional details?
1. What is the exact version of GSA you are using?
2. If this is a pre 7.2 GSA, do you see additional feed on feeds page? When running against 7.0 GSA, adaptor sends ACLs in feeds as named resources (by attaching ?generated to DocId). Don't shutdown Adaptor immediately. Adaptor takes upto 5 mins or more to push named resources in feeds.
3. If you increase logging level to FINER, adaptor will log all the headers which adaptor is sending in response to GSA crawl request. Please share logs to analyze this further.

Regards,
Tanmay

**Comment by rlambrechts** [comment]
Apparently they arrived a little bit later. (~15 mins) so now there is an ACL showing. (as described in 2). Thank you.

Version: Software Version: 7.2.0.G.252

However the Security at Serve Time remains 'Public', despite the fact that I set: 

```
@Override
    public void getDocContent(Request req, Response resp) throws IOException {
        resp.setSecure(true);
...
```

And my ACL rules aren't applied when I search for these items. How come these ACLs aren't enforced in the front-end?

**Comment by PapaJoltOmega** [comment]
It does take some time for the ACL to be processed before it is displayed in administration console.  Access controls are routinely tested; perhaps open a case with Google support engineering team to investigate this particular circumstance?  Thank you
