### ISSUE TITLE
Add metadata to Record

### ISSUE THREAD

**Issue by bithazard** [googlegsa/library#10]
It would be great, to be able to add metadata to Records (com.google.enterprise.adaptor.DocIdPusher.Record) so that you can push real metadata-and-url feeds to the GSA (as opposed to just ACL and URL feeds). Would this be a change that would be accepted as pull request? Or is this functionality not in the library on purpose?

**Comment by PapaJoltOmega** [comment]
It was deliberate choice to have all metadata come at crawl time.

There are three options:
(1)Send metadata in feed, no metadata at crawl.
(2)No metadata in feed, all medata at crawl.
(3)Allowing both.

(1) does not work because some adaptors are graph traversal (eg SharePoint adaptor). It also has undesirable update characteristics for non-graph traversal adaptors.

(3) does not work well because if someone uses both then each overrides the other.

So (2) was chosen.

The value of developer being able to choose whether they do (1) or (2) is clear. Maybe it is worth the risks. I'm not sure.

**Comment by bithazard** [comment]
Understood and agreed. My thinking behind that was that there are certain content systems where you have access to some properties only (or at least very easily) when you initially query all documents but not when you query one particular document later. The usual solution to this is to cache the documents at the initial query and use that cache later to get the information for each individual document. Sending those information in the initial feed would make this caching unnecessary. 

The problem with this of course would be that this meta data would not be available on the GSA if the GSA would crawl a document without getting a feed for this document first. The only way I could think of to prevent this would be to return all documents with the noFollow header set. But this is probably also not a very universal solution. 

That being said option (2) was probably a good choice. Perhaps we (or someone else) will come up with a good solution regarding the described issue without the disadvantages.

**Comment by bithazard** [comment]
Just realized that I can also close the issue, which I will do, as my initial request does not seem to be such a good idea anymore. Feel free to add any thoughts/ideas/insight though ;-).

**Comment by PapaJoltOmega** [comment]
> Perhaps we (or someone else) will come up with a 
> good solution regarding the described issue without 
> the disadvantages.

The use case which is driving my thinking now is DB
adaptor. I'd like to support situations where customer
has URLs+metadata in their DB and doesn't want the
connector to be crawled (instead URL is to be crawled
directly). Essentially a way to make metadata-and-url
feed files while still getting the benefits of schedules
and other configuation features.

It would be nice to add library feature, but that's likely
to require more thinking than adding functionality to
the DB adaptor.

Thank you,
PJ

**Comment by myk-google** [comment]
This was just completed;  Adaptor Library changes [here](https://github.com/googlegsa/library/commit/62be0dadc174be5e8e6ae146a7adf2009e1ff0c0) and DB Adaptor changes [here](https://github.com/googlegsa/database/commit/231d6ea0af2fd1bce94c273213c99d8bdf317e46).
