### ISSUE TITLE
Prevent setting "gsa.scoringType" to empty/invalid value

### ISSUE THREAD

**Issue by bithazard** [googlegsa/library#11]
When you set "gsa.scoringType" in the adaptor-config.properties to an empty value ("gsa.scoringType=") the adaptor also returns the HTTP header "X-gsa-doc-controls: scoring" with an empty value. This leads to an error on the GSA. The pages are not indexed and the Index Diagnostics for a page just shows an Unknown Error. 

It would be good if the adaptor would log an error message or even terminate when "gsa.scoringType" is configured to an invalid value (neither content nor web).

**Comment by PapaJoltOmega** [comment]
Done.

https://github.com/googlegsa/library/commit/841d5acb9da880ee793cc14c4b7b0d715c0ccb78
