### ISSUE TITLE
Bug to add metadata with more than 1500 bytes (class com.google.enterprise.adaptor.Metadata doesn't keep the order of the values)

### ISSUE THREAD

**Issue by samuelzvir** [googlegsa/library#2]
Using the method `com.google.enterprise.adaptor.Metadata.set(String k, Set<String> v);` we lost the order of the metatag values because the method instantiates a new TreeSet that sorts the values using compareTo method re-ordering the values:
 [javadoc](https://docs.oracle.com/javase/7/docs/api/java/util/TreeSet.html)
_"Constructs a new tree set containing the elements in the specified collection, sorted according to the natural ordering of its elements. All elements inserted into the set must implement the Comparable interface. Furthermore, all such elements must be mutually comparable: e1.compareTo(e2) must not throw a ClassCastException for any elements e1 and e2 in the set."_ 

``` java
/** 
   * Make copy of v be the values associated with key. 
   * @param k key
   * @param v set of values of which none are null
   */
  public void set(String k, Set<String> v) {
    if (null == k) {
      throw new NullPointerException();
    }
    if (null == v) {
      throw new NullPointerException();
    }
    assureNoNulls(v);
    if (v.isEmpty()) {
      mappings.remove(k);
    } else {
      v = new TreeSet<String>(v);
      mappings.put(k, v);
    }
  }
```
- To solve this, we need to remove the line `v = new TreeSet<String>(v);`

**Comment by PapaJoltOmega** [comment]
The sorting is intentional.
